### ISSUE TITLE
emacsclient support

### ISSUE THREAD

**Issue by d1egoaz** [prathik/emacs-anywhere#1]
https://github.com/prathik/emacs-anywhere/blob/f10e783dd0603ed8750bd3588ee90d9489620ba0/bin/run#L56

would be good to add a configuration option or open by default `emacsclient` instead of the emacs instance.

I did this to open a new `emacsclient` frame:
```
/usr/local/bin/emacsclient -c $TMPFILE
```

**Comment by larstvei** [comment]
I came here to suggest this 👍

It seems the program doesn't really work if Emacs is already open – or it forces you to close Emacs before it is copied to the clipboard (which is a drag when you have a session going). With `emacsclient` you just go `C-x #` and you're good. Sadly it does require you to have a server running (`M-x start-server` or just keep `(start-server)` in the init-file).

I sent a PR following @d1egoaz's suggestion, changing it to:
```sh
/usr/local/bin/emacsclient -c $TMPFILE || open -W -a Emacs $TMPFILE
```
so that it preserves the original behavior if no server is running.

**Comment by diego-alvarez-hs** [comment]
@larstvei lol, I ended creating my own fork, https://github.com/d1egoaz/vim-anywhere
as eventually I'll add support for linux (OSX at work, Linux at home)

I also added some tweaks to my fork

**Comment by prathik** [comment]
I tried running `/usr/local/bin/emacsclient -c $TMPFILE` from within the script and it isn't loading the file on the emacs server, however chaging to `/usr/local/bin/emacsclient $TMPFILE` is working. It loads the file on emacs server and `C-x #` leads to refocusing on the main application. Will test it out a bit and push the changes.

**Comment by prathik** [comment]
I have pushed the changes suggested by @larstvei
